<a href="https://colab.research.google.com/github/javohuz/Data_Science_and_AI/blob/main/NumPy/NumPy_final_exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np
np.version
np.show_config

<function numpy.__config__.show()>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr3 = np.zeros(9)
arr3


array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr4 = np.array([2,3,4,5,7,7,5,6,4,3], dtype=np.int8)
arr4_1 = np.array([2,3,4,5,7,7], dtype=np.int64)
arr4_2 = np.array([2,3,4,5,7,7], dtype='S')
print(arr4.itemsize, arr4_1.itemsize ,arr4_2.itemsize)


1 8 1


#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)
np.info(np.dot) # .......

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr6 = np.zeros(12)
arr6[5] = 1
arr6

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr7 = np.arange(20,60)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr8 = np.arange(10)
arr8_1 = -np.sort(-arr8)
arr8_2 = arr8[::-1].copy()
print(arr8_1 , ',' ,arr8_2)

[9 8 7 6 5 4 3 2 1 0] , [9 8 7 6 5 4 3 2 1 0]


#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr9 = np.arange(9).reshape(3,3)
arr9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [12]:
arr10 = np.array([3, 7, 0, 0, 9, 0])
arr11 = arr10[arr10 != 0]
nonzero = np.nonzero(arr10)
print(arr11, arr10[nonzero])


[3 7 9] [3 7 9]


#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr11 = np.random.random(8).reshape(2,2,2)
arr11

array([[[0.44690977, 0.41975965],
        [0.67604324, 0.32187381]],

       [[0.65874855, 0.48093355],
        [0.99523735, 0.43846639]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr12 = np.random.random(81).reshape(9,9)
print(np.max(arr12) , np.min(arr12))


0.9943585539221544 0.01797243710249341


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan => NaN
np.nan == np.nan => False
np.inf > np.nan => False
np.nan - np.nan  => NaN
np.nan in set([np.nan]) => True
0.7 == 7 * 0.1 => False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr10_0 = np.arange(18).reshape(6,3)
arr10_1 = np.ones(12).reshape(3,4)
dot = np.dot(arr10_0, arr10_1)
dot

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1)) # python sum 9
from numpy import *
print(sum(range(5),-1)) # numpy sum 10 , axis = -(1)

10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [20]:
a = np.array([1,2])
b = np.array([4,5])

c= a > b

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [23]:
a=np.array(0) / np.array(0)
b=np.array(0) // np.array(0)
c=np.array([np.nan]).astype(int).astype(float)
print(a,b,c)

nan 0 [-9.22337204e+18]


<ipython-input-23-894266350285>:1: RuntimeWarning: invalid value encountered in divide
  a=np.array(0) / np.array(0)
<ipython-input-23-894266350285>:2: RuntimeWarning: divide by zero encountered in floor_divide
  b=np.array(0) // np.array(0)


#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [25]:
arr19 = np.array([3,5,73,2,4,67,3,344])
arr19_1 = np.array([3,73,3,4,63,3,334])
resalt = np.intersect1d(arr19 , arr19_1)
resalt

array([ 3,  4, 73])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

TypeError: as_strided() missing 1 required positional argument: 'x'

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`